### PR TITLE
Gs 565 pyspark example

### PR DESCRIPTION
**Pull request by DeepwaterCreations**

### CODE REVIEW

**Review by jaredwinick — APPROVED** [review]
I haven't tried it out but if it runs successfully, i approve!

**Comment by DeepwaterCreations** [comment]
Don't merge yet - the addon isn't uploading properly. Not sure if it's an issue with the Maven packaging instructions, or what.

**Comment by DeepwaterCreations** [comment]
Everything is sorted out and it should be ready for merging.

**Comment by DeepwaterCreations** [comment]
Just going to go ahead and merge this one, since it's only an example after all - we can always go back and fix it if need be.

**Pull request merged**
